/**
 * Query init command implementation.
 *
 * Generates a skeleton YAML query file with helpful comments.
 */
import { writeFile as fsWriteFile, access, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { generateQueryJSONSchema } from "../../../query/json-schema.js";

/**
 * Sanitize a title string into a safe filename (without extension).
 */
export function sanitizeForFilename(title: string): string {
  const result = title
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9_-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  if (!result) {
    throw new Error('Title produces an empty filename after sanitization');
  }
  return result;
}

/**
 * The YAML template string with comments preserved.
 * This is a raw string (not generated by a YAML library) so comments are kept.
 */
export const QUERY_SCHEMA_FILENAME = "query.schema.json";

// prettier-ignore
const QUERY_TEMPLATE =
  `# yaml-language-server: $schema=./${QUERY_SCHEMA_FILENAME}\n` +
  "name: my_search\n" +
  "description: \"\"\n" +
  "\n" +
  "query:\n" +
  "  - id: concept-1             # Unique block identifier (for provider replacements)\n" +
  "    field: title_abstract    # title, abstract, title_abstract, author, keyword, all\n" +
  "    terms:\n" +
  "      keywords:\n" +
  "        - \"search term 1\"\n" +
  "        - \"search term 2\"\n" +
  "      # mesh:                 # PubMed MeSH terms (optional)\n" +
  "      #   - \"MeSH Heading\"\n" +
  "      # eric:                 # ERIC Descriptors (optional, ERIC only)\n" +
  "      #   - \"ERIC Descriptor\"\n" +
  "      exclude: []             # Terms to exclude (NOT operator)\n" +
  "      # Tip: Use exclude to filter out false matches from short keywords/acronyms\n" +
  "      # exclude:\n" +
  "      #   - \"unwanted term\"\n" +
  "      #   - \"irrelevant topic\"\n" +
  "    operator: OR             # How to combine terms within this block\n" +
  "\n" +
  "  # Add more blocks — blocks are AND'd together\n" +
  "  # - id: concept-2\n" +
  "  #   field: title_abstract\n" +
  "  #   terms:\n" +
  "  #     keywords:\n" +
  "  #       - \"another term\"\n" +
  "  #   operator: OR\n" +
  "\n" +
  "# filters:                   # Optional: apply to all databases\n" +
  "#   year_from: 2020\n" +
  "#   year_to: 2026\n" +
  "#   language:\n" +
  "#     - en\n" +
  "#   publication_types:\n" +
  "#     exclude:\n" +
  "#       - \"Review\"\n" +
  "#       - \"Comment\"\n" +
  "\n" +
  "# providers:                 # Optional: per-database block replacements & filter additions\n" +
  "#   pubmed:\n" +
  "#     replaces:\n" +
  "#       concept-1:           # Replace block by id\n" +
  "#         field: keyword\n" +
  "#         terms:\n" +
  "#           mesh:\n" +
  "#             - \"MeSH Heading\"\n" +
  "#         operator: OR\n" +
  "#     adds:\n" +
  "#       filters:\n" +
  "#         publication_types:\n" +
  "#           exclude:\n" +
  "#             - \"Letter\"\n";

/**
 * Generate the query template YAML string.
 *
 * @param title - Optional title to set as the query name
 * @returns The YAML template string with comments
 */
export function generateQueryTemplate(title?: string): string {
  if (!title) return QUERY_TEMPLATE;
  return QUERY_TEMPLATE.replace('name: my_search', `name: ${title}`);
}

export const QUERIES_DIR = "queries";

export interface WriteQueryTemplateOptions {
  title: string;
  output?: string | undefined;
  stdout?: boolean | undefined;
  force?: boolean | undefined;
  cwd?: string | undefined;
}

/**
 * Write the query template to a file or return it as a message.
 *
 * Output priority:
 * 1. --stdout → return template as message (no file)
 * 2. -o <path> → write to that path
 * 3. default → write to queries/<sanitized-title>.yaml
 */
export async function writeQueryTemplate(options: WriteQueryTemplateOptions): Promise<{ success: boolean; message: string; outputPath?: string }> {
  const template = generateQueryTemplate(options.title);

  if (options.stdout) {
    return { success: true, message: template };
  }

  // Determine output path
  const outputPath = options.output
    ?? join(options.cwd ?? process.cwd(), QUERIES_DIR, `${sanitizeForFilename(options.title)}.yaml`);

  // Check if file exists (unless force is set)
  if (!options.force) {
    try {
      await access(outputPath);
      return {
        success: false,
        message: `File already exists: ${outputPath}. Use --force to overwrite.`,
      };
    } catch {
      // File does not exist, proceed
    }
  }

  // Ensure parent directory exists
  await mkdir(dirname(outputPath), { recursive: true });

  // Write template
  await fsWriteFile(outputPath, template, "utf-8");

  // Generate JSON Schema file alongside output
  const schemaPath = join(dirname(outputPath), QUERY_SCHEMA_FILENAME);
  const jsonSchema = generateQueryJSONSchema();
  await fsWriteFile(schemaPath, JSON.stringify(jsonSchema, null, 2) + "\n", "utf-8");

  return {
    success: true,
    message: `Created: ${outputPath}`,
    outputPath,
  };
}
