/**
 * Query init command implementation.
 *
 * Generates a skeleton YAML query file with helpful comments.
 */
import { writeFile as fsWriteFile, access } from "node:fs/promises";
import { dirname, join } from "node:path";
import { generateQueryJSONSchema } from "../../../query/json-schema.js";

/**
 * Sanitize a title string into a safe filename (without extension).
 */
export function sanitizeForFilename(title: string): string {
  const result = title
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9_-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  if (!result) {
    throw new Error('Title produces an empty filename after sanitization');
  }
  return result;
}

/**
 * The YAML template string with comments preserved.
 * This is a raw string (not generated by a YAML library) so comments are kept.
 */
export const QUERY_SCHEMA_FILENAME = "query.schema.json";

// prettier-ignore
const QUERY_TEMPLATE =
  `# yaml-language-server: $schema=./${QUERY_SCHEMA_FILENAME}\n` +
  "name: my_search\n" +
  "description: \"\"\n" +
  "\n" +
  "query:\n" +
  "  - id: concept-1             # Unique block identifier (for provider replacements)\n" +
  "    field: title_abstract    # title, abstract, title_abstract, author, keyword, all\n" +
  "    terms:\n" +
  "      keywords:\n" +
  "        - \"search term 1\"\n" +
  "        - \"search term 2\"\n" +
  "      # mesh:                 # PubMed MeSH terms (optional)\n" +
  "      #   - \"MeSH Heading\"\n" +
  "      # eric:                 # ERIC Descriptors (optional, ERIC only)\n" +
  "      #   - \"ERIC Descriptor\"\n" +
  "      exclude: []             # Terms to exclude (NOT operator)\n" +
  "      # Tip: Use exclude to filter out false matches from short keywords/acronyms\n" +
  "      # exclude:\n" +
  "      #   - \"unwanted term\"\n" +
  "      #   - \"irrelevant topic\"\n" +
  "    operator: OR             # How to combine terms within this block\n" +
  "\n" +
  "  # Add more blocks — blocks are AND'd together\n" +
  "  # - id: concept-2\n" +
  "  #   field: title_abstract\n" +
  "  #   terms:\n" +
  "  #     keywords:\n" +
  "  #       - \"another term\"\n" +
  "  #   operator: OR\n" +
  "\n" +
  "# filters:                   # Optional: apply to all databases\n" +
  "#   year_from: 2020\n" +
  "#   year_to: 2026\n" +
  "#   language:\n" +
  "#     - en\n" +
  "#   publication_types:\n" +
  "#     exclude:\n" +
  "#       - \"Review\"\n" +
  "#       - \"Comment\"\n" +
  "\n" +
  "# providers:                 # Optional: per-database block replacements & filter additions\n" +
  "#   pubmed:\n" +
  "#     replaces:\n" +
  "#       concept-1:           # Replace block by id\n" +
  "#         field: keyword\n" +
  "#         terms:\n" +
  "#           mesh:\n" +
  "#             - \"MeSH Heading\"\n" +
  "#         operator: OR\n" +
  "#     adds:\n" +
  "#       filters:\n" +
  "#         publication_types:\n" +
  "#           exclude:\n" +
  "#             - \"Letter\"\n";

/**
 * Generate the query template YAML string.
 *
 * @returns The YAML template string with comments
 */
export function generateQueryTemplate(): string {
  return QUERY_TEMPLATE;
}

/**
 * Write the query template to a file or return it as a message.
 *
 * @param options - Output options
 * @param options.output - File path to write to (if omitted, returns template in message)
 * @param options.force - Whether to overwrite existing files
 * @returns Result with success status and message
 */
export async function writeQueryTemplate(options: {
  output?: string;
  force?: boolean;
}): Promise<{ success: boolean; message: string }> {
  const template = generateQueryTemplate();

  if (!options.output) {
    // No output file specified, return template as message
    return { success: true, message: template };
  }

  // Check if file exists (unless force is set)
  if (!options.force) {
    try {
      await access(options.output);
      // File exists and force is not set
      return {
        success: false,
        message: `File already exists: ${options.output}. Use --force to overwrite.`,
      };
    } catch {
      // File does not exist, proceed
    }
  }

  // Write to file
  await fsWriteFile(options.output, template, "utf-8");

  // Generate JSON Schema file alongside output
  const schemaPath = join(dirname(options.output), QUERY_SCHEMA_FILENAME);
  const jsonSchema = generateQueryJSONSchema();
  await fsWriteFile(schemaPath, JSON.stringify(jsonSchema, null, 2) + "\n", "utf-8");

  return {
    success: true,
    message: `Template written to ${options.output}`,
  };
}
