import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  getLogFilePath,
  appendLogEntry,
  readLogEntries,
  type CountLogEntry,
  type PreviewLogEntry,
  type AssessmentLogEntry,
} from './iteration-log.js';

let testDir: string;

beforeEach(async () => {
  testDir = await mkdtemp(join(tmpdir(), 'iteration-log-test-'));
});

afterEach(async () => {
  await rm(testDir, { recursive: true, force: true });
});

describe('getLogFilePath', () => {
  it('should return .search-log.yaml path for a query file', () => {
    expect(getLogFilePath('/path/to/my-search.yaml')).toBe(
      '/path/to/my-search.search-log.yaml'
    );
  });

  it('should handle query files in current directory', () => {
    expect(getLogFilePath('query.yaml')).toBe('query.search-log.yaml');
  });

  it('should handle .yml extension', () => {
    expect(getLogFilePath('/path/to/query.yml')).toBe(
      '/path/to/query.search-log.yaml'
    );
  });
});

describe('appendLogEntry', () => {
  it('should create file with header comment if not exists', async () => {
    const queryFile = join(testDir, 'my-search.yaml');
    await writeFile(queryFile, 'name: test\n', 'utf-8');

    const entry: CountLogEntry = {
      date: '2026-02-16 10:30',
      type: 'count',
      query_hash: 'abc123',
      counts: { pubmed: 50000, scopus: 42000 },
      total: 92000,
    };

    await appendLogEntry(queryFile, entry);

    const logPath = getLogFilePath(queryFile);
    const content = await readFile(logPath, 'utf-8');

    expect(content).toContain('# Search iteration log for my-search.yaml');
    expect(content).toContain('type: count');
    expect(content).toContain('query_hash: abc123');
    expect(content).toContain('pubmed: 50000');
    expect(content).toContain('total: 92000');
  });

  it('should append to existing file', async () => {
    const queryFile = join(testDir, 'my-search.yaml');
    await writeFile(queryFile, 'name: test\n', 'utf-8');

    const entry1: CountLogEntry = {
      date: '2026-02-16 10:30',
      type: 'count',
      query_hash: 'abc123',
      counts: { pubmed: 50000 },
      total: 50000,
    };

    const entry2: AssessmentLogEntry = {
      date: '2026-02-16 10:35',
      type: 'assessment',
      verdict: 'reject',
      comment: 'Too broad, need more specific MeSH terms',
    };

    await appendLogEntry(queryFile, entry1);
    await appendLogEntry(queryFile, entry2);

    const logPath = getLogFilePath(queryFile);
    const content = await readFile(logPath, 'utf-8');

    // Should contain both entries
    expect(content).toContain('type: count');
    expect(content).toContain('type: assessment');
    expect(content).toContain('verdict: reject');
    expect(content).toContain('Too broad');
  });

  it('should append preview entry with titles', async () => {
    const queryFile = join(testDir, 'search.yaml');
    await writeFile(queryFile, 'name: test\n', 'utf-8');

    const entry: PreviewLogEntry = {
      date: '2026-02-16 11:00',
      type: 'preview',
      query_hash: 'def456',
      counts: { pubmed: 100 },
      total: 100,
      titles: {
        pubmed: ['Title 1', 'Title 2', 'Title 3'],
      },
    };

    await appendLogEntry(queryFile, entry);

    const logPath = getLogFilePath(queryFile);
    const content = await readFile(logPath, 'utf-8');

    expect(content).toContain('type: preview');
    expect(content).toContain('Title 1');
    expect(content).toContain('Title 2');
  });
});

describe('readLogEntries', () => {
  it('should return empty array when no log file exists', async () => {
    const queryFile = join(testDir, 'nonexistent.yaml');
    const entries = await readLogEntries(queryFile);
    expect(entries).toEqual([]);
  });

  it('should parse existing log entries', async () => {
    const queryFile = join(testDir, 'my-search.yaml');
    await writeFile(queryFile, 'name: test\n', 'utf-8');

    const logPath = getLogFilePath(queryFile);
    const logContent = `# Search iteration log for my-search.yaml
# Auto-generated by search-hub.

- date: "2026-02-16 10:30"
  type: count
  query_hash: abc123
  counts:
    pubmed: 50000
    scopus: 42000
  total: 92000

- date: "2026-02-16 10:35"
  type: assessment
  verdict: reject
  comment: "Too broad, need more specific MeSH terms"
`;
    await writeFile(logPath, logContent, 'utf-8');

    const entries = await readLogEntries(queryFile);
    expect(entries).toHaveLength(2);

    const countEntry = entries[0] as CountLogEntry;
    expect(countEntry.type).toBe('count');
    expect(countEntry.query_hash).toBe('abc123');
    expect(countEntry.counts['pubmed']).toBe(50000);
    expect(countEntry.total).toBe(92000);

    const assessEntry = entries[1] as AssessmentLogEntry;
    expect(assessEntry.type).toBe('assessment');
    expect(assessEntry.verdict).toBe('reject');
    expect(assessEntry.comment).toBe('Too broad, need more specific MeSH terms');
  });

  it('should return empty array for log file with only comments', async () => {
    const queryFile = join(testDir, 'my-search.yaml');
    const logPath = getLogFilePath(queryFile);
    await writeFile(
      logPath,
      '# Search iteration log\n# Empty\n',
      'utf-8'
    );

    const entries = await readLogEntries(queryFile);
    expect(entries).toEqual([]);
  });

  it('should preserve manual comments in log file through append', async () => {
    const queryFile = join(testDir, 'my-search.yaml');
    await writeFile(queryFile, 'name: test\n', 'utf-8');

    const logPath = getLogFilePath(queryFile);
    const logContent = `# Search iteration log for my-search.yaml
# Manual note: first iteration

- date: "2026-02-16 10:30"
  type: count
  query_hash: abc123
  counts:
    pubmed: 50000
  total: 50000
`;
    await writeFile(logPath, logContent, 'utf-8');

    // Append a new entry
    const entry: AssessmentLogEntry = {
      date: '2026-02-16 10:35',
      type: 'assessment',
      verdict: 'reject',
      comment: 'Too broad',
    };
    await appendLogEntry(queryFile, entry);

    // Verify comments are preserved
    const content = await readFile(logPath, 'utf-8');
    expect(content).toContain('# Manual note: first iteration');
    expect(content).toContain('type: count');
    expect(content).toContain('type: assessment');
  });
});
