/**
 * Query iteration log I/O.
 *
 * Reads and appends entries to a search iteration log file
 * that lives alongside the query YAML file.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { parse, stringify } from 'yaml';

// ── Types ───────────────────────────────────────────────────────────

export interface CountLogEntry {
  date: string;
  type: 'count';
  query_hash: string;
  counts: Record<string, number>;
  total: number;
}

export interface PreviewLogEntry {
  date: string;
  type: 'preview';
  query_hash: string;
  counts: Record<string, number>;
  total: number;
  titles: Record<string, string[]>;
}

export interface AssessmentLogEntry {
  date: string;
  type: 'assessment';
  verdict?: string;
  precision?: string;
  comment?: string;
}

export type LogEntry = CountLogEntry | PreviewLogEntry | AssessmentLogEntry;

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Derive the log file path from a query file path.
 * `{dir}/{basename}.yaml` → `{dir}/{basename}.search-log.yaml`
 */
export function getLogFilePath(queryFilePath: string): string {
  const dir = dirname(queryFilePath);
  const base = basename(queryFilePath).replace(/\.ya?ml$/, '');
  const logName = `${base}.search-log.yaml`;
  return dir === '.' ? logName : join(dir, logName);
}

/**
 * Generate a timestamp in "YYYY-MM-DD HH:mm" format.
 */
export function formatTimestamp(date: Date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

// ── Read / Write ────────────────────────────────────────────────────

/**
 * Read raw content of the log file, preserving comments.
 * Returns null when the file does not exist.
 */
async function readRawLog(logPath: string): Promise<string | null> {
  try {
    return await readFile(logPath, 'utf-8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

/**
 * Read log entries from the iteration log file for a given query file.
 * Returns an empty array when the log file does not exist or is empty.
 */
export async function readLogEntries(queryFilePath: string): Promise<LogEntry[]> {
  const logPath = getLogFilePath(queryFilePath);
  const content = await readRawLog(logPath);

  if (content === null || !content.trim()) {
    return [];
  }

  const parsed = parse(content);

  // YAML with only comments parses to null
  if (parsed === null || parsed === undefined) {
    return [];
  }

  if (!Array.isArray(parsed)) {
    return [];
  }

  return parsed as LogEntry[];
}

/**
 * Append a log entry to the iteration log file.
 * Creates the file with a header comment if it does not exist.
 */
export async function appendLogEntry(
  queryFilePath: string,
  entry: LogEntry,
): Promise<void> {
  const logPath = getLogFilePath(queryFilePath);
  const queryBasename = basename(queryFilePath);
  const existing = await readRawLog(logPath);

  // Stringify the single entry as a YAML sequence item
  const entryYaml = stringify([entry], { lineWidth: 0 }).trimEnd();

  let content: string;
  if (existing === null) {
    const header =
      `# Search iteration log for ${queryBasename}\n` +
      `# Auto-generated by search-hub. You can also edit this file manually.\n\n`;
    content = header + entryYaml + '\n';
  } else {
    const trimmed = existing.trimEnd();
    content = trimmed + '\n\n' + entryYaml + '\n';
  }

  await writeFile(logPath, content, 'utf-8');
}
