/**
 * review mark command - Mark decisions in review/work files
 */

import { readFile, writeFile } from 'node:fs/promises';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { ReviewDecision, ReviewFile, WorkFile, ArticleEntry } from './types.js';

export interface ReviewMarkOptions {
  /** Path to the work file */
  file: string;
  /** Article ID to mark */
  id?: string;
  /** Decision to apply */
  decision?: ReviewDecision;
  /** Optional comment */
  comment?: string;
}

export interface ReviewMarkResult {
  /** Number of articles marked */
  marked: number;
  /** Warnings (e.g., articles not found) */
  warnings: string[];
}

/**
 * Extract leading comment lines from YAML content (lines starting with #)
 */
function extractLeadingComments(content: string): string {
  const lines = content.split('\n');
  const commentLines: string[] = [];
  for (const line of lines) {
    if (line.startsWith('#') || line.trim() === '') {
      commentLines.push(line);
    } else {
      break;
    }
  }
  // Return empty string if no comments found
  if (commentLines.length === 0) return '';
  return commentLines.join('\n') + '\n';
}

/** @deprecated Detects old WorkFile format (flat id/decision fields). Kept for backward compat. */
function isWorkFile(file: unknown): file is WorkFile {
  if (
    typeof file !== 'object' ||
    file === null ||
    !('basis' in file) ||
    !('articles' in file) ||
    !Array.isArray((file as WorkFile).articles)
  ) {
    return false;
  }
  const articles = (file as WorkFile).articles;
  if (articles.length === 0) return false;
  const first = articles[0]!;
  return 'id' in first && 'decision' in first && !('reviews' in first);
}

/**
 * Find article by identifier (doi, pmid, scopusId, arxivId, ericId, title)
 */
function findArticleByIdentifier(id: string, articles: ArticleEntry[]): ArticleEntry | undefined {
  for (const article of articles) {
    if (article.doi && article.doi.toLowerCase() === id.toLowerCase()) return article;
    if (article.pmid && article.pmid === id) return article;
    if (article.scopusId && article.scopusId === id) return article;
    if (article.arxivId && article.arxivId === id) return article;
    if (article.ericId && article.ericId === id) return article;
    if (article.title.toLowerCase() === id.toLowerCase()) return article;
  }
  return undefined;
}

/**
 * Execute review mark command
 */
export async function executeReviewMark(options: ReviewMarkOptions): Promise<ReviewMarkResult> {
  if (!options.id || !options.decision) {
    throw new Error('--id and --decision must be specified');
  }

  const rawContent = await readFile(options.file, 'utf-8');
  const parsed = parseYaml(rawContent);

  const result: ReviewMarkResult = {
    marked: 0,
    warnings: [],
  };

  if (isWorkFile(parsed)) {
    // Old WorkFile format (backward compat)
    const workFile = parsed as WorkFile;
    const article = workFile.articles.find((a) => a.id === options.id);
    if (!article) {
      throw new Error(`Article not found: ${options.id}`);
    }
    article.decision = options.decision;
    if (options.comment !== undefined) {
      article.comment = options.comment;
    }
    result.marked = 1;

    const yamlContent = stringifyYaml(workFile, { lineWidth: 0 });
    const leadingComments = extractLeadingComments(rawContent);
    await writeFile(options.file, leadingComments + yamlContent, 'utf-8');
  } else {
    // New ReviewFile screening format
    const reviewFile = parsed as ReviewFile;

    if (!reviewFile.basis) {
      throw new Error(
        'Invalid review file: missing "basis" field. This command only works with files generated by "review extract --basis".',
      );
    }

    const article = findArticleByIdentifier(options.id, reviewFile.articles);
    if (!article) {
      throw new Error(`Article not found: ${options.id}`);
    }

    // Ensure reviews array exists with at least one entry
    if (!article.reviews || article.reviews.length === 0) {
      article.reviews = [{ decision: 'uncertain', comment: '' } as ArticleEntry['reviews'][0]];
    }

    // Update first review entry
    article.reviews[0]!.decision = options.decision;
    if (options.comment !== undefined) {
      article.reviews[0]!.comment = options.comment;
    }
    result.marked = 1;

    const yamlContent = stringifyYaml(reviewFile, { lineWidth: 0 });
    const leadingComments = extractLeadingComments(rawContent);
    await writeFile(options.file, leadingComments + yamlContent, 'utf-8');
  }

  return result;
}
