/**
 * review mark command - Mark decisions in work files
 */

import { readFile, writeFile } from 'node:fs/promises';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { ReviewBasis, ReviewDecision } from './types.js';

/**
 * Work file article entry
 */
interface WorkFileArticle {
  id: string;
  title: string;
  abstract?: string;
  decision: ReviewDecision | null;
  comment: string;
}

/**
 * Work file structure
 */
interface WorkFile {
  sessionId: string;
  basis: ReviewBasis;
  reviewer: string;
  articles: WorkFileArticle[];
}

/**
 * Decision input for batch marking
 */
interface DecisionInput {
  id: string;
  decision: ReviewDecision;
  comment?: string;
}

export interface ReviewMarkOptions {
  /** Path to the work file */
  file: string;
  /** Article ID to mark (for single marking) */
  id?: string;
  /** Decision to apply (for single marking) */
  decision?: ReviewDecision;
  /** Optional comment (for single marking) */
  comment?: string;
  /** Path to JSON file with decisions (for batch marking) */
  input?: string;
}

export interface ReviewMarkResult {
  /** Number of articles marked */
  marked: number;
  /** Warnings (e.g., articles not found) */
  warnings: string[];
}

/**
 * Load work file
 */
async function loadWorkFile(filePath: string): Promise<WorkFile> {
  const content = await readFile(filePath, 'utf-8');
  const workFile = parseYaml(content) as WorkFile;

  // Validate that this is a work file (has basis field)
  if (!workFile.basis) {
    throw new Error('Invalid work file: missing "basis" field. This command only works with work files generated by "review extract --basis".');
  }

  return workFile;
}

/**
 * Save work file
 */
async function saveWorkFile(filePath: string, workFile: WorkFile): Promise<void> {
  const content = stringifyYaml(workFile, { lineWidth: 0 });
  await writeFile(filePath, content, 'utf-8');
}

/**
 * Execute review mark command
 */
export async function executeReviewMark(options: ReviewMarkOptions): Promise<ReviewMarkResult> {
  const workFile = await loadWorkFile(options.file);

  const result: ReviewMarkResult = {
    marked: 0,
    warnings: [],
  };

  if (options.input) {
    // Batch marking from JSON input
    const inputContent = await readFile(options.input, 'utf-8');
    const decisions = JSON.parse(inputContent) as DecisionInput[];

    for (const decision of decisions) {
      const article = workFile.articles.find((a) => a.id === decision.id);
      if (article) {
        article.decision = decision.decision;
        if (decision.comment !== undefined) {
          article.comment = decision.comment;
        }
        result.marked++;
      } else {
        result.warnings.push(`Article not found: ${decision.id}`);
      }
    }
  } else if (options.id && options.decision) {
    // Single article marking
    const article = workFile.articles.find((a) => a.id === options.id);
    if (!article) {
      throw new Error(`Article not found: ${options.id}`);
    }

    article.decision = options.decision;
    if (options.comment !== undefined) {
      article.comment = options.comment;
    }
    result.marked = 1;
  } else {
    throw new Error('Either --id with --decision, or --input must be specified');
  }

  await saveWorkFile(options.file, workFile);

  return result;
}
